services:
  backend:
    build:
      context: ./backend
    container_name: ${PROJECT_NAME:-simple-auth}-backend
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    env_file: .env

  frontend:
    build:
      context: ./frontend
    container_name: ${PROJECT_NAME:-simple-auth}-frontend
    env_file: .env            # ← reads API_BASE_URL/VITE_API_BASE_URL from the shared root .env
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    depends_on:
      - backend
